Melhoria 37 - adiciona titulo em todas as telas
angelicaameira/EasyDecision pull request #48
Opened 2021-09-06 20:18 UTC by angelicaameira

fixes #37

2021-09-07 11:54 UTC, antoniogermano requested changes
É necessário fazer as mudanças solicitadas

2021-09-07 11:54 UTC, antoniogermano commented on EasyDecision/Decisao/controler/AdicionaCriterioViewController.swift
> +        }else {
Corrigir espaçamento do else

2021-09-07 11:54 UTC, antoniogermano commented on EasyDecision/Decisao/controler/AdicionaDecisaoViewController.swift
> +        }else {
Corrigir espaçamento do else

2021-09-07 11:54 UTC, antoniogermano commented on EasyDecision/Decisao/controler/AdicionaOpcaoViewController.swift
> +        }else {
Corrigir espaçamento do else

2021-09-07 11:54 UTC, antoniogermano commented on EasyDecision/Decisao/controler/DecisaoTableViewController.swift
> +//            if segue.identifier == "adicionarDecisao" {
Revisão de código para ir para a branch principal: se não está sendo usado, apague o código comentado. Se será necessário, coloque TODO. Se deveria ser usado, des-comente

2021-09-07 13:00 UTC, angelicaameira commented
feito

2021-09-12 14:18 UTC, antoniogermano approved these changes
Pode fazer o merge

2021-09-12 14:51 UTC, merged